# Generated by Django 4.1.3 on 2022-11-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='symbol',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
